# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 816c7bf88593c0ad3370a62fd9d8aea6a7575652b42afa9ead106036a25bc43ac0ba5f30ac3ca4191c70eb87c33b54cdac3103c043f0d576c16e70263f7b0a56

test:
  secret_key_base: ed885ac2e4c64a98b44c27a84d102f6e67554475a430fcf354919acff041dbd12d65af60f43cbc103d8b1397664b05f110c50721d8ad19dbf79325ce65247ba9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
